In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.preprocessing import MinMaxScaler
from sklearn.naive_bayes import GaussianNB

In [2]:
file=pd.read_csv("iris.csv")

In [3]:
file

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [4]:
X=file.values[:,:-1]
X.shape

(150, 4)

In [43]:
Y=file.values[:,:-1]
Y.shape


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3.0, 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5.0, 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5.0, 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3.0, 1.4, 0.1],
       [4.3, 3.0, 1.1, 0.1],
       [5.8, 4.0, 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1.0, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5.0, 3.0, 1.6, 0.2],
       [5.0, 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [45]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=3)
X_train


array([[6.4, 3.2, 4.5, 1.5],
       [5.1, 3.3, 1.7, 0.5],
       [6.0, 2.7, 5.1, 1.6],
       [5.8, 2.7, 5.1, 1.9],
       [5.4, 3.0, 4.5, 1.5],
       [4.8, 3.0, 1.4, 0.3],
       [5.0, 3.2, 1.2, 0.2],
       [5.8, 2.7, 5.1, 1.9],
       [7.0, 3.2, 4.7, 1.4],
       [6.1, 2.8, 4.7, 1.2],
       [4.9, 3.1, 1.5, 0.2],
       [6.3, 3.4, 5.6, 2.4],
       [5.1, 3.8, 1.5, 0.3],
       [6.5, 3.0, 5.5, 1.8],
       [5.7, 2.9, 4.2, 1.3],
       [5.0, 3.6, 1.4, 0.2],
       [4.8, 3.0, 1.4, 0.1],
       [6.8, 3.2, 5.9, 2.3],
       [5.9, 3.2, 4.8, 1.8],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [5.1, 2.5, 3.0, 1.1],
       [6.4, 3.1, 5.5, 1.8],
       [6.3, 3.3, 6.0, 2.5],
       [4.9, 3.1, 1.5, 0.1],
       [6.7, 3.3, 5.7, 2.1],
       [5.7, 3.0, 4.2, 1.2],
       [4.7, 3.2, 1.6, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [7.4, 2.8, 6.1, 1.9],
       [7.7, 3.8, 6.7, 2.2],
       [5.8, 2.8, 5.1, 2.4],
       [5.7, 2.8, 4.1, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [6.3, 2

In [46]:
Y_train

array([[6.4, 3.2, 4.5, 1.5],
       [5.1, 3.3, 1.7, 0.5],
       [6.0, 2.7, 5.1, 1.6],
       [5.8, 2.7, 5.1, 1.9],
       [5.4, 3.0, 4.5, 1.5],
       [4.8, 3.0, 1.4, 0.3],
       [5.0, 3.2, 1.2, 0.2],
       [5.8, 2.7, 5.1, 1.9],
       [7.0, 3.2, 4.7, 1.4],
       [6.1, 2.8, 4.7, 1.2],
       [4.9, 3.1, 1.5, 0.2],
       [6.3, 3.4, 5.6, 2.4],
       [5.1, 3.8, 1.5, 0.3],
       [6.5, 3.0, 5.5, 1.8],
       [5.7, 2.9, 4.2, 1.3],
       [5.0, 3.6, 1.4, 0.2],
       [4.8, 3.0, 1.4, 0.1],
       [6.8, 3.2, 5.9, 2.3],
       [5.9, 3.2, 4.8, 1.8],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [5.1, 2.5, 3.0, 1.1],
       [6.4, 3.1, 5.5, 1.8],
       [6.3, 3.3, 6.0, 2.5],
       [4.9, 3.1, 1.5, 0.1],
       [6.7, 3.3, 5.7, 2.1],
       [5.7, 3.0, 4.2, 1.2],
       [4.7, 3.2, 1.6, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [7.4, 2.8, 6.1, 1.9],
       [7.7, 3.8, 6.7, 2.2],
       [5.8, 2.8, 5.1, 2.4],
       [5.7, 2.8, 4.1, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [6.3, 2

In [41]:
DTClassifer=DecisionTreeClassifier()

In [42]:
DTClassifer.fit(X_train,Y_train)

ValueError: Unknown label type: 'unknown'